### ISSUE TITLE
Issue building ravensw

### ISSUE THREAD

**Issue by martintc** [kraileth/miniraven#3]
Issues is known, but creating it to track it and make comments on it. Output when building on NetBSD, I am assuming this is the same issue you have ran into elsewhere. 

```sh
*** Error code 1

Stop.
make[2]: stopped in /var/ravenbuild/construction/ravensw-647d920/libpkg/repo/binary
*** Error code 1

Stop.
make[1]: stopped in /var/ravenbuild/construction/ravensw-647d920/libpkg/repo
*** Error code 1

Stop.
make: stopped in /var/ravenbuild/construction/ravensw-647d920

stderr: In file included from binary.h:28:0,
                 from binary.c:24:
/var/ravenbuild/construction/ravensw-647d920/libpkg/private/pkg.h:532:2: error: unknown type name ‘FXRETTYPE’
  FXRETTYPE ssh;
```

I think I have an idea of what is going wrong here. Need to do some reading and sit down with the code and play with it. If I get something working I will be sure to upstream it. I am guessing something is going on with a library. Perhaps it is not pulling the correct path or at least the correct path on NetBSD. Placement of things can vary a little.

**Comment by kraileth** [comment]
John gave me a hint about what might be the problem here and pointed me to [this](http://www.ravenports.com/catalog/bucket_AD/fetch/library/). That's where estream stuff comes from. Indeed it looks like I missed this dependency for ravensw when I started working on miniraven (and configure seems not to check for it)! Either that or an older version of ravensw didn't require it, yet. Don't remember. Stupid oversight, though...

Ironically, here goes cmake again! Will try to get the library built without it, though.

**Comment by kraileth** [comment]
@martintc Status update: After building LibreSSL PIC libs and installing those, ravensw starts linking as there are no more missing files. Mini_manifest is wrong because I wanted to always rebuild libressl while I worked on it and forgot about it. Next commit will fix that.

As far as FreeBSD is concerned, now the problem is that ravensw fails to link due to encountering duplicate symbols! I've never hit something weird like that before and fear that figuring out what goes on there it is beyond me. Errors that come up are like this:

```
ld: error: duplicate symbol: nbactions
>>> defined at add.c                                                                  
>>>            add.o:(nbactions)
>>> defined at alias.c
>>>            alias.o:(.bss+0x0)

ld: error: duplicate symbol: nbdone
>>> defined at add.c
>>>            add.o:(nbdone)
>>> defined at alias.c
>>>            alias.o:(.bss+0x4)
```

How can symbols of the same name end up being defined in multiple c files in a way that they conflict with each other? Have you ever seen this happen?

**Comment by martintc** [comment]
That is odd, I started working on this on NetBSD and am hitting some weird errors. I think I am stuck at the pic_lib. When I run ./configure --debug on ravensw, I get an error that libarchive_pic.a can not be found.

The duplicate symbols sound odd. I will give it a shot building it from scratch on FreeBSD.

**Comment by kraileth** [comment]
@martintc Are you running the command mentioned above via the shell? If so you must keep in mind that the environment needs to match what miniraven sets for it to be able to pick up the libraries. There's the default stuff defined for both configure and make stages at the very bottom of `nest.conf` (ignore gcc6-aux if you come across it - it's a leftover from my first take at automating the build. Need to delete that.). Also in the `[configure_cmds]` section you'll find the "env XYZ" call that sets e.g. LDFLAGS to `-L$$TGT_PREFIX$$/lib` (i.e. /raven/lib by default). With those things set, it should be able to pick up libarchive_pic.a.

**Comment by martintc** [comment]
Ah that makes sense, I didn't think about raven and mini raven needing a special set. I figured it would just use the default libarchive set provided by FreeBSD which looks like the interface is the same as libarchive on NetBSD. Will definitely give this a look.

Since ravensw that is pulled from miniraven gets cleaned up between each run and pulled down, I have a local copy of ravensw from the git repo. I have been playing with the files, compressing it and passing it in as distinfo to the conf file to pull from.

Example from nest.conf

Ravensw = /home/test/ravensw.tar.go

Writing this on my phone

**Comment by martintc** [comment]
Quick question, do you know where the source files for these libs are? I may hit an issue with they are compiled on FreeBSD and NetBSD and FreeBSD are not binary compatible, so I may need to build things like libarchive_pic first before trying to boot strap ravensw

**Comment by kraileth** [comment]
It's regular libarchive, if I'm not mistaken. John originally patched it to include zstd support, but since that has been included in upstream libarchive, Raven is using the standard version. The line to build libarchive as defined in nest.conf is the following:

```
env PATH=$$TGT_PREFIX$$/bin:/usr/bin:/bin:/usr/sbin:/sbin make, ar -cruv libarchive_pic.a /var/ravenbuild/construction/libarchive-3.5.1/libarchive/.libs/*.o, ranlib libarchive_pic.a
```
So after you built libarchive regularly, you build the libarchive_pic.a library by hand using `ar` and then generating an index with `ranlib`.

**Comment by martintc** [comment]
Just noticed something building ravensw from miniraven. On NetBSD is fails at a line of code calling
```c
struct statfs fs
```
NetBSD appears to have deprecated where this structure is being called from, however I may be able to write a work around in the code for this. Ill give it a shot. I can only find a reference in the man pages when looking at man pages from NetBSD-2.1.

If I can get that fixed and it compiles, Ill make an actual fork of ravensw and make the changes, then try to upstream it to John and get feedback from him.

**Comment by kraileth** [comment]
> NetBSD appears to have deprecated where this structure is being called from, however I may be able to write a work around in the code for this. Ill give it a shot. I can only find a reference in the man pages when looking at man pages from NetBSD-2.1.

Found one hit in `libpkg/pkg_jobs.c`, is that right? Dunno if it is a relatively recent part of pkg or if it has been in there for a long time. If the latter - it might help to take a look at what John did about it, when he ported pkg(8) over for the pkgsrc-synth project. According to his description, it was "lightly tested" on NetBSD, but that means it must have compiled and provided basic functionality.

Took a look at the tree and found the directory [for pkg](https://github.com/jrmarino/pkgsrc-synth/tree/master/pkgtools/pkg). The relevant lines seem not to have changed from the old version of pkg. And I didn't see a patch for that specific file, either. But it looks like `nbcompat` was required to make it build on NetBSD. Either that or it's just needed in the pkgsrc context. Perhaps you know.

**Comment by martintc** [comment]
Looking into it right now. It was those lines in pkg_jobs.c. Trying to a fix right now. Essentially there is a pre-processor if-else going on. If it is sun, it does one thing, if not the other. On NetBSD it would hit this else condition and try to use `statfs.` I am trying to insert another condition for `#if __NetBSD__` with what should be the relevant code. But I will take a look at that directory and see what else I can find.

**Comment by martintc** [comment]
Alright, so went with distributing myself my own copy of ravensw to test my changes, however I hit an issue. Instead of taking out the checks for md5, I just generated new hashes and placed them in nest.conf.

Running it to build ravensw, I now get this error for env
```sh
Build missing packages now? (Y/N) y

Fetching "libressl-3.2.5.tar.gz"... ok
Extracting "libressl-3.2.5.tar"... ok
Configuring "libressl"... ok
Building "libressl"... ok
Installing "libressl"... ok
Fetching "jrmarino-ravensw-647d920.tar.gz"... ok
Extracting "jrmarino-ravensw-647d920.tar"... ok
Fetching "sqlite-autoconf-3280000.tar.gz"... ok
Configuring "ravensw"... 
Error: Shell execution failed!
stdout: 
stderr: env: ./configure: No such file or directory
```

**Comment by kraileth** [comment]
Two hints for you:

1) Edit nest.conf and remove the `ravensw` definitions in the sections `[distfile_md5]` and `[distfile_umd5]` (both entire lines). I made checksums optional exactly for cases like this. If they are available they will be calculated and compared against, if they are missing this step will simply be skipped.

2) Look for the `ravensw` line in section `[configure_cmds]`. Change the definition e.g. to `pwd, ls, false`, then run miniraven again. It sounds that either the commands don't get executed in /var/ravenbuild/construction/ravensw-647d920 or there's no `configure` file there.

**Comment by martintc** [comment]
Ah, I didn't look to see if the md5 hashes were optional. I did get it working by placing my own hashes, but knowing this will make it easier as I poke and prod at the ravensw code!

**Comment by martintc** [comment]
Found my issue here. It was a naming difference. I was just taring up ravensw as jrmarino-ravensw-(some versioning scheme), when I tar ravensw-(some versioning scheme), then everything works properly. So now I am making progress on testing out my patch

**Comment by martintc** [comment]
So my patch to pkg_jobs.c works, now I am hitting errors in pkg_elf.c, plan to keep trying to work through these until I get ravensw built on NetBSD. Then compile that down and then we can reach out to John about what all I did and work with him to get an acceptable patch into ravensw. Once we get there, I am thinking we should tackle ravenadm.
